In [2]:
import torch
import torch.nn as nn

In [16]:
class LinearRegression(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        self.linear = nn.Linear(input_size, output_size)
    def forward(self, x):
        return self.linear(x)

In [30]:
torch.manual_seed(1)
model = LinearRegression(1, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [31]:
model.forward(torch.tensor([2.0]))


tensor([0.5891], grad_fn=<AddBackward0>)