In [1]:
import torch
from torch.nn import Linear

In [18]:
torch.manual_seed(3)
model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.7889], requires_grad=True) Parameter containing:
tensor([[-0.9915]], requires_grad=True)


In [22]:
x = torch.tensor([[4.8], [10.0]])
print(model(x))

tensor([[ -5.5479],
        [-10.7036]], grad_fn=<AddmmBackward0>)
