In [1]:
import torch

##### Multi Dimensional Tensors (Matrix)

In [4]:
one_dimensional_tensor = torch.arange(0, 9)
print(one_dimensional_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [6]:
two_dimensional_tensor = one_dimensional_tensor.view(3, 3)
print(two_dimensional_tensor, f"Tensor dimension: {two_dimensional_tensor.dim()}")

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) Tensor dimension: 2


In [9]:
two_dimensional_tensor[:, 0]

tensor([0, 3, 6])

In [11]:
three_dimensional_tensor = torch.arange(0, 18).view(2, 3, 3)
print(three_dimensional_tensor, f"Tensor dimension: {three_dimensional_tensor.dim()}")

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]) Tensor dimension: 3


##### Slicing Multi Dimensional Tensors

In [15]:
three_dimensional_tensor_for_slicing = torch.arange(36).view(3, 4, 3)
three_dimensional_tensor_for_slicing

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]])

In [16]:
print(f"getting 19: {three_dimensional_tensor_for_slicing[1, 2, 1]}")

tensor(19)

In [17]:
print(f"getting second tensor: {three_dimensional_tensor_for_slicing[1]}")

getting second tensor: tensor([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]])


##### Matrix Multiplication

In [21]:
first_matrix = torch.tensor([2, 3, 4, 1, 6, 8]).view(2, 3)
second_matrix = torch.tensor([9, 11, 4, 6, 1, 4]).view(3, 2)
print(f"matrix multiplication: {torch.matmul(first_matrix, second_matrix)}")
print(f"matrix multiplication in another way: {first_matrix @ second_matrix}")

matrix multiplication: tensor([[34, 56],
        [41, 79]])
matrix multiplication in another way: tensor([[34, 56],
        [41, 79]])


 ##### Gradient

In [22]:
x = torch.tensor([2.0], requires_grad=True )
y = 9*x**4 + 4*x**3 + 6*x**2
y.backward()
x.grad

tensor([360.])

##### Partial Gradient

In [27]:
x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([6.0], requires_grad=True)
y = x**2 + 2*z**3
y.backward()
z.grad

tensor([216.])